apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mon-loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-ops
  source:
    repoURL: 'https://github.com/DFPartner/fabric-infra.git'
    targetRevision: HEAD
    path: platform/monitoring/loki/overlays/df-test
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true