apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: platform-ops
  source:
    repoURL: 'https://github.com/BoraPerusic/k3s-df.git'
    targetRevision: HEAD
    path: apps/templates
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
