apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: platform-ops
  source:
    repoURL: 'https://github.com/BoraPerusic/k3s-df.git'
    targetRevision: HEAD
    path: clusters/bp-dsk
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true      # Delete things in cluster that are removed from Git
      selfHeal: true   # Fix things in cluster if someone changes them manually