---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAz79tdclgvPKEYJQzEeM3yngGD/Qb/xgBoqQtlD2jtiWlXhHC7V71dqZGanhL/6aA3kyBMPOGL2OsAU2FiVOUf9oty9f78NBU/9o+ukOeexHyawi07+jMeUG7r3m4sbwvPNwmX6Iu1g723lPS6rwQ6kn6B8ZAWPWy/NCiPIdGtHXJyM/DcTmlYUESzbGppB7ZqBNZgnUjHevhTT2aPPwAri1kVIxujgoxZDuMprZFrGkyxUS3RUIA15qRj3jglZ2UGj6u8ubg4+9fAvWaN2PGAw8h4/4Nk5wi9/X8+vyPAJpJ9mdJ+MYQZnP30+iRope1BbZ74UqBZLOU7jXACyQmBSovxP/SCD0TQ1DOk0/PU2vBum+ZfBv+tClNG69vtDGBj451jrv/+XZeAj7fS3bXaHKrjykpYveGkLhGKSiQ5zD+l4ekctIyPy4khuqXW4NKygu7yumuquTTyyq8XaJ0+K1GQJXe00cgUV0TksMHhijLzJl1gvGQC7VpuZzVXd2TNI1cqotbfzdKi1mKux8EtBVNTFt7KjAMDu30jrfwmkT3CALm6M8peyO84lEYzyPefLoRIQu4j5dBYjdM+SVzNVBe69i7refKcNTKR++XKXKdthbT0O6iNnghC4cO/kdin80pKwoMYJM/AmA6A1AZVBs90p04hhM2rf2SJkQBFSMJk1vrhtWMB7NoMoc6m1/DilCRIag5DZJOt2+DqZuXjdb0ppCHxvi4=
    admin-user: AgBlnUaR/1EI1cM1yLpy2F+aNLVxn3qFYdwYj+SvOVS+TRP7Z8SA0W95GFwIKw2T/tO0MSHUns1dRDTsrd9sWcs336bYGUUksnHyB/QAoJ6r3dP+KPif48hGrbMto4QmvcyKwXzjqA7VBM0xFuZMDLjkrHBBARAqDZbbTGcTaHlunPTWgFR68z27mxrgnC+4fZdtEgauRezYNOQYXO9LfKHseE0cARx6npQKDMj5HfyBaYQJLHWW+6F0UVF80nigiUzg3SaigTy2x+EdPu4zfJuPyAb66n/ensTJZbvfDTmmNSkkEWufk59B8b1t9HLw38+ylGdOvTuH5wK8zjd1UeBiB6z5EsrTjqOFAX7gMmeaKO8yTTLN3b+y68+aX+eogEeLoFa0j/HCGcb5mUv8iP7XrAjxxkylHudNu2CL6jWp4SNcrjqW9vgaxUshbDZ6Je8rAV36rm7TNyOrj4c5iSk8gvaAzVN56wKBy4N6Tb4fhRrO5ZTj22p6eHzq05lQMLf/rGWsjX3YbVbw+fzFxaAUF6P3x2y0rAjeg7bM2l6KvvLiKEs0Kk76V0IKAOJacc+e9QLBnu33nbmvh8gByn/BC1ThXid/tY1rvNspSFPbNglk2XZIdn3bnJNtHVZuFpsQ59vfr9bQ3op5PLWcj9/aQVPL/S7c4lHYTpCSMxxWOrFykKXQTQG8NXLZbf8PN8nrCuW1hQ==
  template:
    metadata:
      name: grafana-admin-creds
      namespace: monitoring
