---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-creds
  namespace: monitoring
spec:
  encryptedData:
    access_key_id: AgBLb0ZGalZfdTSo73p2jpYlqrgCSE/0LzODcV6taP2ck2qsRWZHxNCZKTwoRLD6qpK8vBBPF/5YIXN+aye3Qm1mMCJQ3riMzEhp5X/eySnFDeDhLsPN7noeXqWhv4sQsoFQGgWkdly4aX5PhxZQCQNhWRuzwjXPelNEIZXbBF7o3GeIr7XhqMkxwAfw3o9DE+Qy3n5iOlTXa0aQk9Nqkez6GgyMli2oNHVOE/LssOzWTKIGJlmHWAFaZrcSGI0IGKSaaWu85l+mBssLBXqRmdVM4io3R4jwI8D2fEz7bLnGfgeJaDtSLXYUX7ZjiVNmPnU/7RX3D0vr7RbKcnJeepOyrqEHIb+1EwRwHoLufDecEc4gZD1aVnd7gQte8ie1cY7/wCHSf89tn16JX/JlXjUE6dlf5aGOhuSduXizKEwQEt84tRo2h4bbdgcN+idLWRB2uDWN+p6RtsbMrrPJ0CJSxzkm62zZOX8e1l0mAeFRLBKVSx3v2b6Qq/AEMkVXnZCOApA1YL4katKNuuTx5FRuf4I5zRMrErgcZNk3LfAGWXqYJJaFZ26U2vqqavkPgEtDKRUq5iZA3yWaPXvgp/F0M2g/ToVttLKBmVfwtaLRQesZBm2y+ne4siSKWjrGd0mbBrtABd4ychUFqlSZizwVBPKbfdqg1sG1j1GtbuyhMqiIA+ucDSTQnIRinDc9GpAx1W5QbQ==
    secret_access_key: AgCjsVizPJOodP+U7Q/wgh9Xp36zJElLTG86RbicZL1fNoxXW0UKHzRNapacQzPCKJU1SMBPwGHohRnFrpyMoEndP9/EIAqTb4yyQCdb3Y+VQo/a+avkIwhL60yGiV7efNMTsNGOZ8ZFF7LdOyy7ymWi/aPyPobu8rM6YjM7VPLe3jE9yBC3nsIrtW2MJkmera6LnDgzUaB6XAQeb7TD1D8E/p29dLn86u+bsaCQIczO95CNnwYdiX7SMA04sDvjU6alpxwztxmSyNY57JujkMB26q/289icyMqhSBEmZY3HHHIVMCBbCDCw+zckhL5GwyFK7U1pb+F7YzrXOXUpLDbaXr/767PLYYlkn9vO0y7XR4JKL658U/r22qoWLf/23IxnoqW8xyqE0hyBPYngvzJBx4Gk6BE/gzZCh3zfO0a/vq2C5/djlMN9NomgX7BLWGNs4ZK9+0yLYL52jdVi6YMNy9N3eIVlR0Ysw5GZlAIC5pGVcY6MPbGWeJtq0yPQPz7asoFeKezvyenpbafk7np+zHaP2bV0ud4fTANcnZpmDHmZr0irjwn0DvMrU/xHQFDZR4rE9XkiMUtrBR2do6BnS1bUT5NkdIdL2tihYj+3QnPOB+qkwmMauAKUt21YgMlBCc9DTmwEB5+g8OKSKE7WwYvkGpfFhqpxOfG3Hkr2jT1TjnnqqWzhATdUYQpVurppQRV0o+BsWafUDtW0OOapdJjT
  template:
    metadata:
      name: monitoring-creds
      namespace: monitoring
