apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-sealed-secrets
  namespace: argocd
spec:
  project: platform-ops
  source:
    repoURL: 'https://github.com/DFPartner/fabric-infra.git'
    targetRevision: HEAD
    path: platform/auth/sealed-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true