apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mon-grafana
  namespace: argocd
spec:
  project: platform-ops
  source:
    repoURL: 'https://github.com/BoraPerusic/k3s-df.git'
    targetRevision: HEAD
    path: platform/monitoring/grafana/overlays/bp-dsk
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true