apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mon-prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-ops
  source:
    repoURL: 'https://github.com/BoraPerusic/k3s-df.git'
    targetRevision: HEAD
    path: platform/monitoring/prom-stack/overlays/local
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true