apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: df-tst-root-ca
  namespace: auth
spec:
  isCA: true
  commonName: "DF Test Kubernetes CA"
  secretName: root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io