apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-postgres
  namespace: argocd
spec:
  project: platform-ops
  source:
    repoURL: 'https://github.com/BoraPerusic/k3s-df.git'
    targetRevision: HEAD
    path: platform/auth/db/overlays/bp-dsk
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true