---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-creds
  namespace: auth
spec:
  encryptedData:
    admin-password: AgBcndJ+KNX1nks7fUUL+8pH3FK90+ib4kaozrdcG5InSbU4BDingSKibGjx3GAFrYrtRdurfNiu6GUyIbEj6sQ8nTxca1IlWl9aa2IVOBYRnMlrbhW8Meh/8IFKYmw5oWJpIAbtXAmPuaV7+mV5XG4Thtu3HwHnHIvWPXaNqZBJjDjDuBc+TCnt77Xt9Nqh6sKA/h6u+guaUBZdjafX/RmPEe3PYAEeZ4yQWNdhkhv7i9/TcMOmowNkXyEvFc/0wGmdy5zxxAlo4eUlVlTMed+ICP7EHMDD4sMLFrirPPUFPsJ4p6m5/8OoajcUR6OpuuITI9yzYnz8cF2d36XUOSElMIqvR2hzj2E8MD97eE5KndZDKPRCoU/QSHTaVXYuiyBJ8lzlG/B9wDEMJ0iU0itix7m/YQfL0ZvEaSPaPYE5irx5EWeKKXniQE2z11147cltNVaqFfl4TDaBp1NQS/Z2HEdbuI438VKuF30Ut+xMEgbhms2ad30TQgU9kIn61JYXDoJW15YhsZgOINNOAvdPLLcGL4BDMfB98UTR3VVo1oDqiMVlqhIwuCQ7dGOPSq/MYOzCtk6mZiIFfc3EtmC/v/p11atTA55/UQl4m9gdAlbpUzvfdIa2nMtShomGT2X6ZD5TPVWs8LT8WNz5qq2wtRbHAN411NmWR1bNx3bGCx6+VSIkw/cX+kN1oNdd4hZKVNKgbZupvKUz+gxRtHWb3LlMAkaUbUpN
  template:
    metadata:
      name: keycloak-admin-creds
      namespace: auth
